try {
    console.log('here is no error');
    // console.log(x);
    console.log('checking this');
} catch (err) {
    console.log(err);
    console.log('the error occured');
} finally {
    console.log('this will always be executed')
}